name: CI

on: [push, pull_request]

jobs:
  build:
    # Test on ubuntu
    runs-on: ubuntu-latest

    steps:
      # This project have submodules to checkout
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      # Run configuration before `make`
      - name: Pre-build
        run: |
          ./autogen.sh
          ./configure --with-device=ch4:ofi
      
      # Apply Coderrect Scanner
      - name: Coderrect Scan
        uses: coderrect-inc/coderrect-github-action@v0.4
